name: Bug Report
description: Create a report to help project development.
title: "[BUG] You'r title"
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Description about bug and how you've got it
    validations:
      required: true
  - type: textarea
    id: bug-reproduce
    attributes:
      label: How to reproduce bug
      description: A clear description how to reproduce bug.
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information and data
      description: |
        Screenshots, tests log and etc.
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: Operating System
      description: Which operating system are you using (e.g., Windows/Linux/Mac OS)?
    validations:
      required: true
