[workspace]
members = [
  "tplc",
  "tpl-lexer",
  "tpl-parser",
  "tpl-ir",
]
resolver = "2"

[workspace.package]
version = "0.3.1"
authors = ["mealet <workjason34@gmail.com>"]
description = "Toy Programming Language - simple programming language written in Rust Lang"
