[workspace]
members = [
  "tplc",
  "tpl-lexer",
  "tpl-parser",
]

[workspace.package]
version = "0.1.2"
authors = ["mealet <workjason34@gmail.com"]
description = "Toy Programming Language - simple programming language written in Rust Lang"
