[package]
name = "tplc"
version = "0.1.0"
authors.workspace = true
description = "Main Compiler Module for TPL Language"
edition = "2021"

[dependencies]
tpl-lexer = { path = "../tpl-lexer" }
tpl-parser = { path = "../tpl-parser" }
