[package]
name = "tpl-ir"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
inkwell = { version = "0.5.0", features = ["llvm14-0"] }
tpl-parser = { path = "../tpl-parser" }
