[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "linker=clang",
  "-C", "link-arg=-fuse-ld=lld",
  "-Zlocation-detail=none",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-Zlocation-detail=none"
]

[target.x86_64-windows-msvc]
rustflags = [
  "-Zlocation-detail=none"
]
